learning_log/learning_log/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url    #记得导入包
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'', include('learning_logs.urls',namespace='learning_logs')),
]

learning_log/learning_logs/urls.py
#learning_logs  urls
from django.conf.urls import url
from . import views
#from django.urls import path

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^topics/$',views.topics,name='topics'),
    url(r'^topics/(?P<topic_id>\d+)$',views.topic,name='topic'),
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)$',views.new_entry,name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)$',views.edit_entry,name='edit_entry'),
]

app_name = 'learning_logs'

learning_log/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views
urlpatterns=[

    url(r'^login/$',LoginView.as_view(template_name='users/login.html'),name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$',views.register,name='register'),

]
app_name = 'users'

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    owner=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='entries'

    def __str__(self):
        return self.text[:50]+"..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic,Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text':''}


class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=['text']
        labels={'text':''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}

learning_log/learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,"learning_logs/index.html")

@login_required
def topics(request):
    topics= Topic.objects.filter(owner=request.user).order_by('date_added')
    content={'topics':topics}
    return render(request,"learning_logs/topics.html",content)

@login_required
def topic(request,topic_id):
    topic= Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries=topic.entry_set.order_by('date_added')
    content={'topic':topic,'entries':entries}
    return render(request,"learning_logs/topic.html",content)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form=TopicForm(request.POST)
        if form.is_valid():
            new_topic=form.save(commit=False)
            new_topic.owner=request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    content={'form':form}
    return render(request,'learning_logs/new_topic.html',content)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    content={'topic':topic,'form':form,'topic_id':topic_id}
    return render(request,'learning_logs/new_entry.html',content)

@login_required
def edit_entry(request,entry_id):
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form=EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

    content={'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',content)

learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    if request != 'POST':
        form=UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            authenticate_user=authenticate(username=new_user.username,password=request.POST['password'])
            login(request,authenticate_user)
            return  HttpResponseRedirect(reverse('learning_logs:index'))


    content={'form':form}
    return render(request,'users/register.html',content)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatiable" content="IE=edge">
    <meta name="Viewport" content="width=device-width,initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<nav class="navbar-default navbar-static-top">
    <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-togle collapsed"
        data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">
        </button>
    <a class="navbar-brand"    href="{% url 'learning_logs:index' %}">Learning Log</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
    <a href="{% url 'learning_logs:topics' %}">Topic</a>
    </ul>

    <ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
        Hello,{{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
    </ul>
    </div>
</nav>
<div class="container">
    <div  class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
    {% block content %}{% endblock content %}
    </div>
</div>

</body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
    <p><a href="% url 'learning_logs:topic' topic.id %">{{ topic }}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}"  method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add changes</button>
    </form>

{% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block header %}
    <div class="jumbotron">
    <h1>Track your learning.</h1>
{% endblock header %}
{% block content %}
    <a href="{% url 'users:register' %}">Register an account</a>
 <p>Learning Log</p>
 <p>Learning Log helps you keep track of your learning,for any topic you're learning about.</p>
{% endblock content %}

</body>
</html>

learning_log/learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
    <p><a href="% url 'learning_logs:topic' topic.id %">{{ topic }}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}"  method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>

{% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block header %}
        <h2>Add a new topic.</h2>
{% endblock header %}
{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}"  method='post' class="form">
        {% csrf_token %}
        {{%  bootstrap_form form %}}
        {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block header %}

    <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
 <p>Topic:{{ topic}}</p>
 <p>Entries:</p>
 <p>
     <a href="{% url 'learning_logs:new_entry' topic_id %}">Add a new entry:</a>
 </p>
 <ul>
     {% for entry in entries %}
         <div class="panel panel-default">
            <div class="panel-heading">
           <h3> {{ entry.date_added|date:'M d, Y H:i'}}
           <small>
               <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry:</a>
           </small>
          </h3>
            </div>
         <div>
            {{ entry.text|linebreaks }}
         </div>
         </div>
     {% empty %}
        <li>No entries have been added yet for this topic.</li>
     {% endfor %}
 </ul>
{% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block header %}
        <h1>Topics.</h1>
{% endblock header %}
{% block content %}
 <p>Topics</p>
 <ul>
     {% for topic in topics %}
        <li>
            <h3>
            <a href="% url 'learning_logs:topic' topic.id %">{{ topic }}</a>
            </h3>
        </li>
     {% empty %}
        <li>No topics have been added yet.</li>
     {% endfor %}
 </ul>
    <h3><a href="% url 'learning_logs:new_topic' topic_id %">Add a new topic:</a></h3>
{% endblock content %}
</body>
</html>

learning_log/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <div class="jumbotron">
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'users:login'  %}"  method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit">login</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{%  url 'learning_logs:index' %}"  />
    </form>

{% endblock content %}
</body>
</html>

learning_log/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}


    <form action="{% url 'users:register'  %}"  method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{%  url 'learning_logs:index' %}"  />
    </form>

{% endblock content %}
</body>
</html>